version: "3.9"
services:
  rp:
    build: .
    ports:
      - "8080:443"
    extra_hosts:
      - host.docker.internal:host-gateway
    volumes:
      - ./oidc.conf:/usr/local/apache2/conf/oidc.conf
      - ./htdocs:/usr/local/apache2/htdocs
      - ../../localhost+1-key.pem:/ssl/key.pem
      - ../../localhost+1.pem:/ssl/cert.pem
